name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    name: Build
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest  

    env:
      Solution_Name: src\WebAppDonne\WebAppDonne.sln         # Substitua pelo nome da sua solução, ou seja, MyWpfApp.sln.
      Test_Project_Path: test\Test.Donne\Test.Donne.csproj   # Substitua pelo caminho do seu projeto de teste, ou seja, MyWpfApp.Tests\MyWpfApp.Tests.csproj.
     
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3.2.0

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Execute unit tests
      run: dotnet test $env:Test_Project_Path --no-build --verbosity normal

    - name: Publish
      run: dotnet publish src/WebAppDonne/WebApi.Donne.csproj -c Release -o website
